### ISSUE TITLE
Plans for PyCuddle?

### ISSUE THREAD

**Issue by caseykneale** [ChrisRackauckas/Cuddle.jl#6]
I like the idea of this, a lot actually. But, I really want all of the python packages imported into my environment too. Are there plans for a PyCuddle?

**Comment by ChrisRackauckas** [comment]
No. Troll.

**Comment by caseykneale** [comment]
You think I'm trolling but really I'm getting ready to scrape: https://pypi.org/search/?c=Programming+Language+%3A%3A+Python+%3A%3A+3

**Comment by ChrisRackauckas** [comment]
Is this package a joke to you?
